apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-tag-test
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-tag-test
  template:
    metadata:
      labels:
        app: jenkins-tag-test
    spec:      
      containers:
      - name: jenkins-tag-test
        image: __IMAGE_NAME__
        env:
        - name: TZ
          value: Asia/Seoul        
        ports:
        - containerPort: 9300
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "500m"            
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-tag-test
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 9300
    targetPort: 9300
    nodePort: 30503
  selector:
    app: jenkins-tag-test